
services:
  datastore:
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:emulators
    command: gcloud beta emulators datastore start --project=test --host-port=0.0.0.0:8081
    ports:
      - 8081:8081

  redis:
    image: redis:8.0
    ports:
      - 6379:6379
